@echo off
echo Starting X Server...
start "" "C:\Program Files\VcXsrv\vcxsrv.exe" :0 -multiwindow -clipboard -nowgl -ac

echo Starting PulseAudio...
start "" "E:\csm\pulseaudio\bin\start-pulseaudio.bat"

echo Waiting for services to start...
timeout /t 5

echo Starting Voice Assistant...
wsl -d Ubuntu-22.04 bash -c "cd ~/voice-assistant && source env/bin/activate && python voiceui.py"